export const generalFaqs : Array<Object>=[
    {
        'faq_id':'1',
        'header':'General',
        'faq':[
            {
                '_id':'1',
                'questions':'question1',
                'answers':'test1',
            },
            {
                '_id':'2',
                'questions':'question2',
                'answers':'test2',
            },
        ],
    },
    {
        'faq_id':'2',
        'header':'Career Navigation',
        'faq':[
            {
                '_id':'1',
                'questions':'deepak',
                'answers':'',
            },
        ],
    },
    {
        'faq_id':'3',
        'header':'Ivy League Program',
        'faq':[
            {
                '_id':'1',
                'questions':'question1',
                'answers':'test1',
            },
            {
                '_id':'2',
                'questions':'question2',
                'answers':'test2',
            },
        ],
    },
    {
        'faq_id':'4',
        'header':'University Placements Program',
        'faq':[
            {
                '_id':'1',
                'questions':'question1',
                'answers':'test1',
            },
            {
                '_id':'2',
                'questions':'question2',
                'answers':'test2',
            },
        ],
    },
    {
        'faq_id':'5',
        'header':'Refund',
        'faq':[
            {
                '_id':'1',
                'questions':'question1',
                'answers':'test1',
            },
            {
                '_id':'2',
                'questions':'question2',
                'answers':'test2',
            },
        ],
    },
];